### ISSUE TITLE
[BUG] Release 1.1.0 was not published

### ISSUE THREAD

**Issue by Nek-12** [kevlar-kt/kevlar#5]
Release 1.1.0 is missing

https://ipv6.repo1.maven.org/maven2/io/github/kevlar-kt/antipiracy/

**Comment by cioccarellia** [comment]
I've forgot to release the staging repo :D

I'd blame the Christmas vacation but it was an oversight. I published them right away.
All theee artifacts should be available soon.

Good catch!
