### ISSUE TITLE
[FR] Provide documentation on building, maintaining and publishing the library

### ISSUE THREAD

**Issue by Nek-12** [kevlar-kt/kevlar#7]
## Feature description
I'm unable to publish to maven local because there is no developer guide, and to build it I had to dig through the build file source code (which is unnecessarily complicated by the way), and searching for missing property, env variables and other stuff that breaks publishing. The library also uses in memory pgp signature instead of pushing keys to a popular pgp key repo. 

### Use cases
I want to maintain my own fork of the library and contribute

**Comment by cioccarellia** [comment]
I didn't mention anywhere, but this project is generated from a template I built that is actually meant to help maintaining and publishing multi-module android library projects.

You can find all documentation and details at https://github.com/cioccarellia/lib-template-android.

With regards to how it was built, the library supports both *Github actions* and *local properties* by using environment variables, this way it is flexible and easy to configure.

Here is a basic `local.properties` configuration:
```
signing.keyId=                # Your GPG Key ID
signing.password=             # Your Key Passphrase
signing.secretKeyRingFile=    # Your GPG Key file path
ossrhUsername=                # Account Username
ossrhPassword=                # Account Password
sonatypeStagingProfileId=     # These two should match, they are your profile id.
stagingProfileId=             # These two should match, they are your profile id.
```
